import { Mail, ShieldCheck } from "lucide-react";
import SEO from "../components/SEO.jsx";
import { company, contact } from "../data/content.js";

export default function PrivacyNotice() {
  return <section className="section privacy-notice-page"><SEO title="Privacy Notice" path="/privacy" description="How Innovex Resource Group Limited collects, uses, protects and retains personal information under UK data protection law." />
    <header className="privacy-notice-hero"><span className="eyebrow"><ShieldCheck size={16} /> UK data protection</span><h1>Privacy Notice</h1><p>How {company.name} uses personal information across recruitment, training, client services, website enquiries and newsletters.</p><small>Last reviewed: 28 August 2026</small></header>
    <div className="privacy-notice-layout"><aside className="card"><strong>Data controller</strong><span>{company.name}</span><span>Company no. {company.companyNumber}</span><span>Registered in {company.registeredIn}</span><span>{contact.address}</span><a href={`mailto:${contact.email}`}>{contact.email}</a><span>{contact.phoneDisplay}</span><p>If you have a privacy question or want to exercise a right, contact us using these details.</p></aside>
      <article className="card privacy-notice-copy">
        <h2>1. Information we collect</h2><p>Depending on your relationship with us, we may collect identity and contact details, business and role information, recruitment and CV information, right-to-work and availability details, communications, service enquiries, transaction records, website form information and newsletter preferences. We do not use special-category information for newsletter profiling.</p>
        <h2>2. Why we use it and our lawful bases</h2><p>We use information to respond to enquiries, provide requested services, manage recruitment and placements, deliver training and business services, maintain security and records, meet legal duties and—where permitted—send relevant direct marketing. Our lawful bases may include consent, contract, legal obligation and legitimate interests. Where we rely on legitimate interests, we assess necessity, proportionality, reasonable expectations and privacy impact.</p>
        <h2>3. Email marketing and PECR</h2><p>For individuals, sole traders and ordinary partnerships, we normally send unsolicited marketing only with consent or where every condition of the soft opt-in applies. Corporate subscribers may receive relevant business-to-business marketing where we have documented an appropriate UK GDPR lawful basis. We identify ourselves in every campaign and provide a working unsubscribe route. An objection or unsubscribe overrides our marketing interest.</p>
        <h2>4. Who receives information</h2><p>Access is limited to authorised Innovex personnel and suppliers that support hosting, email delivery, IT, professional advice and contracted service delivery. We do not sell personal information. Suppliers must protect information and use it only for authorised purposes. If information is processed outside the UK, we use an approved transfer safeguard where required.</p>
        <h2>5. Retention and suppression</h2><p>We keep information only as long as needed for the stated purpose, legal obligations, disputes and defensible business records. Newsletter campaign content and compliance evidence may be retained for audit. When you opt out, we keep the minimum email and preference information on a suppression list so that we can honour your request; we do not use that record to send marketing.</p>
        <h2>6. Security</h2><p>We use role-based access, authenticated administration, encrypted transport, input validation, audit records and access restrictions appropriate to the information. No internet service is risk-free, but we review safeguards and restrict access to people who need it.</p>
        <h2>7. Your rights</h2><p>Depending on the circumstances, you may have rights to be informed, access, rectification, erasure, restriction, portability and objection. You can withdraw consent at any time. You have an absolute right to object to direct marketing. Contact <a href={`mailto:${contact.email}`}>{contact.email}</a>. You may also complain to the UK Information Commissioner’s Office at <a href="https://ico.org.uk/make-a-complaint/" target="_blank" rel="noreferrer">ico.org.uk/make-a-complaint</a>.</p>
        <h2>8. Newsletter choices</h2><p>Every newsletter contains a personal unsubscribe link. You can also email us with “unsubscribe” in the subject. We do not include invisible open-tracking pixels in the Newsletter Centre. Public newsletter archive pages may contain normal website links, and ordinary website security logs may apply when you visit them.</p>
        <h2>9. Changes</h2><p>We may update this notice when services, suppliers or law change. The review date above shows the current version.</p>
        <div className="privacy-contact-strip"><Mail /><span><strong>Privacy request</strong><a href={`mailto:${contact.email}`}>{contact.email}</a></span></div>
      </article></div>
  </section>;
}
