import { ArrowRight, CheckCircle2, FileCheck2, Headphones, LockKeyhole, Network, Scale, ServerCog, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import SEO from "../components/SEO.jsx";
import { company, contact } from "../data/content.js";

const pages = {
  security: { icon: ShieldCheck, eyebrow: "Trust centre", title: "Security built into the workspace.", intro: "Innovex applies layered access, tenant isolation, secure file validation and accountable activity records across the CRM.", sections: [["Access control", "Role-based permissions, server-enforced action controls, MFA support, revocable sessions and CSRF-protected authentication."], ["Data isolation", "Every tenant-scoped CRM query is constrained to its organisation context, including scheduled background work."], ["File protection", "CV files are checked against their real signature, active PDF content is rejected, previews are protected and access is auditable."], ["Operational resilience", "Health monitoring, searchable system events, retention controls, legal holds and recovery-readiness drills support reliable operations."]] },
  terms: { icon: Scale, eyebrow: "Legal", title: "Website and platform terms.", intro: `These terms govern access to ${company.name} public services and contracted software workspaces.`, sections: [["Permitted use", "Use services lawfully, provide accurate information and do not attempt to bypass security, access another workspace or disrupt availability."], ["Accounts", "Workspace users are responsible for protecting credentials, enabling appropriate security controls and promptly reporting suspected compromise."], ["Service scope", "Commercial scope, service levels, fees and customer responsibilities are defined in the signed proposal, order form or service agreement."], ["Liability and law", "Contract-specific liability terms take precedence. These website terms are governed by the laws of England and Wales."]] },
  dpa: { icon: FileCheck2, eyebrow: "Data protection", title: "Data Processing Addendum.", intro: "A UK GDPR-aligned DPA is available for customers where Innovex processes personal data on their behalf.", sections: [["Processing instructions", "Innovex processes customer data only for the contracted service and documented customer instructions."], ["Security measures", "Controls include tenant isolation, restricted access, session security, audit records, retention tooling and secure document handling."], ["Data subject support", "The DPA covers assistance with data subject requests, incident response, deletion or return and regulator enquiries."], ["Execution", `The final DPA, processing details and applicable suppliers are confirmed during contracting. Request a copy from ${contact.email}.`]] },
  subprocessors: { icon: Network, eyebrow: "Transparency", title: "Subprocessor information.", intro: "The exact supplier schedule is confirmed for each hosted customer deployment and attached to the customer DPA.", sections: [["Infrastructure", "Cloud hosting, database and storage providers may process encrypted or access-controlled application data to deliver the service."], ["Communications", "Customer-configured email and calling providers process messages or call metadata only when those features are enabled."], ["Operations", "Monitoring and support providers may receive limited technical event data; form content and CV data are excluded from analytics."], ["Change control", "Contracted customers receive the current named subprocessor schedule and appropriate notice of material supplier changes."]] },
  status: { icon: ServerCog, eyebrow: "Service availability", title: "Platform status.", intro: "Live platform health is continuously checked through the API and operational events are reviewed inside each workspace.", sections: [["Website", "Operational"], ["CRM API", "Operational"], ["Database connectivity", "Monitored"], ["Scheduled reminders", "Tenant-aware queue monitoring enabled"]] },
  support: { icon: Headphones, eyebrow: "Customer success", title: "Support when your team needs it.", intro: "Get practical help with access, workflows, data, implementation and operational questions.", sections: [["General support", `Email ${contact.email} or call ${contact.phoneDisplay} during ${contact.hours}.`], ["Security issue", "Mark your message SECURITY and include the affected workspace, time and a non-sensitive description. Do not email passwords or CV files."], ["Product onboarding", "Workspace mapping, administrator guidance and role configuration are included in the agreed implementation plan."], ["Priority incidents", "Customer-specific response targets and escalation contacts are defined in the applicable service agreement."]] },
  pricing: { icon: LockKeyhole, eyebrow: "Commercial plans", title: "A plan matched to your workflow.", intro: "CRM pricing depends on users, modules, data migration, integrations and implementation scope. Every proposal is transparent before work begins.", sections: [["Starter", "Focused CRM foundation for a small team: core records, pipeline, enquiries and controlled access."], ["Growth", "Connected recruitment and client operations with automation, documents, communications and reporting."], ["Professional", "Advanced security, compliance workflows, portals, integrations and tailored operational dashboards."], ["Enterprise", "Multiple teams or workspaces, custom governance, migration, support commitments and integration planning."]] }
};

export default function ProductPolicyPage({ page }) {
  const content = pages[page] || pages.security;
  const Icon = content.icon;
  return <section className="product-policy-page"><SEO title={content.title.replace(/\.$/, "")} path={`/${page}`} description={content.intro} />
    <header className="product-policy-hero"><span><Icon />{content.eyebrow}</span><h1>{content.title}</h1><p>{content.intro}</p></header>
    <div className="product-policy-grid">{content.sections.map(([title, body]) => <article key={title}><CheckCircle2 /><div><h2>{title}</h2><p>{body}</p></div></article>)}</div>
    <section className="product-policy-cta"><div><small>Need the contractual detail?</small><h2>Talk to Innovex about your organisation.</h2></div><Link to="/contact?service=crm#contact-form">Contact our team <ArrowRight /></Link></section>
  </section>;
}
