import { useEffect, useState } from "react";
import { Activity, Check, CircleAlert, Code2, Copy, KeyRound, Link2, Pause, Play, Plus, RefreshCw, RotateCw, ShieldCheck, Webhook, X } from "lucide-react";
import { api } from "../../api/client.js";
import AdminSectionHero from "../../components/AdminSectionHero.jsx";
import StatusMessage from "../../components/StatusMessage.jsx";
import SubmitButton from "../../components/SubmitButton.jsx";

const scopeLabels = { "jobs:read": "Read vacancies", "candidates:read": "Read candidates", "clients:read": "Read organisations" };

export default function AdminIntegrations() {
  const [data, setData] = useState({ keys: [], endpoints: [], deliveries: [], options: { scopes: [], events: [] }, metrics: {} });
  const [tab, setTab] = useState("api");
  const [status, setStatus] = useState(null);
  const [busy, setBusy] = useState(false);
  const [revealed, setRevealed] = useState(null);
  const [keyForm, setKeyForm] = useState({ name: "", scopes: ["jobs:read"] });
  const [hookForm, setHookForm] = useState({ name: "", url: "", events: ["candidate.created"] });

  async function load() { try { setData(await api("/integrations")); } catch (error) { setStatus({ type: "error", message: error.message }); } }
  useEffect(() => { load(); }, []);
  function toggle(current, value, setter, key) { setter((previous) => ({ ...previous, [key]: current.includes(value) ? current.filter((item) => item !== value) : [...current, value] })); }

  async function createKey(event) {
    event.preventDefault(); setBusy(true); setStatus(null);
    try { const result = await api("/integrations/api-keys", { method: "POST", body: keyForm }); setRevealed({ title: "API key created", label: "API KEY", value: result.apiKey, warning: result.warning }); setKeyForm({ name: "", scopes: ["jobs:read"] }); await load(); }
    catch (error) { setStatus({ type: "error", message: error.message }); } finally { setBusy(false); }
  }

  async function createWebhook(event) {
    event.preventDefault(); setBusy(true); setStatus(null);
    try { const result = await api("/integrations/webhooks", { method: "POST", body: hookForm }); setRevealed({ title: "Webhook ready", label: "SIGNING SECRET", value: result.signingSecret, warning: result.warning }); setHookForm({ name: "", url: "", events: ["candidate.created"] }); await load(); }
    catch (error) { setStatus({ type: "error", message: error.message }); } finally { setBusy(false); }
  }

  async function revokeKey(id) { if (!window.confirm("Revoke this API key? Connected systems will lose access immediately.")) return; try { await api(`/integrations/api-keys/${id}`, { method: "DELETE" }); await load(); } catch (error) { setStatus({ type: "error", message: error.message }); } }
  async function changeEndpoint(endpoint, statusValue) { try { await api(`/integrations/webhooks/${endpoint.id}`, { method: "PATCH", body: { status: statusValue } }); await load(); } catch (error) { setStatus({ type: "error", message: error.message }); } }
  async function rotateSecret(id) { if (!window.confirm("Rotate this signing secret? Existing webhook verification will stop until the receiver is updated.")) return; try { const result = await api(`/integrations/webhooks/${id}/rotate-secret`, { method: "POST" }); setRevealed({ title: "Signing secret rotated", label: "NEW SIGNING SECRET", value: result.signingSecret, warning: result.warning }); } catch (error) { setStatus({ type: "error", message: error.message }); } }
  async function retryDelivery(id) { try { const result = await api(`/integrations/deliveries/${id}/retry`, { method: "POST" }); setStatus({ type: result.status === "Delivered" ? "success" : "error", message: result.message }); await load(); } catch (error) { setStatus({ type: "error", message: error.message }); } }

  return <div className="integrations-page">
    <AdminSectionHero eyebrow="Developer platform" title="API & Webhook Integrations" description="Connect trusted systems through least-privilege API access and signed, observable webhook deliveries." aside={<div className="integrations-health"><ShieldCheck /><span><small>SECURITY MODEL</small><strong>Scoped & signed</strong></span></div>} />
    <StatusMessage status={status} />
    <section className="integration-stats"><article><KeyRound /><span><small>ACTIVE KEYS</small><strong>{data.metrics.activeKeys || 0}</strong></span></article><article><Webhook /><span><small>LIVE ENDPOINTS</small><strong>{data.metrics.activeEndpoints || 0}</strong></span></article><article><Check /><span><small>RECENTLY DELIVERED</small><strong>{data.metrics.delivered || 0}</strong></span></article><article className={data.metrics.attention ? "attention" : ""}><CircleAlert /><span><small>NEEDS ATTENTION</small><strong>{data.metrics.attention || 0}</strong></span></article></section>
    <nav className="integration-tabs"><button className={tab === "api" ? "active" : ""} onClick={() => setTab("api")}><Code2 />API keys</button><button className={tab === "webhooks" ? "active" : ""} onClick={() => setTab("webhooks")}><Webhook />Webhooks</button><button className={tab === "deliveries" ? "active" : ""} onClick={() => setTab("deliveries")}><Activity />Delivery log</button></nav>
    {tab === "api" && <div className="integration-grid"><form className="integration-builder" onSubmit={createKey}><header><span><Plus /></span><div><small>NEW CREDENTIAL</small><h2>Create a scoped API key</h2><p>The complete key is displayed once and stored only as a SHA-256 hash.</p></div></header><label><span>Credential name</span><input value={keyForm.name} onChange={(event) => setKeyForm({ ...keyForm, name: event.target.value })} placeholder="Reporting warehouse" required /></label><fieldset><legend>Allowed scopes</legend>{data.options.scopes.map((scope) => <label key={scope} className="integration-check"><input type="checkbox" checked={keyForm.scopes.includes(scope)} onChange={() => toggle(keyForm.scopes, scope, setKeyForm, "scopes")} /><span><Check />{scopeLabels[scope] || scope}</span><code>{scope}</code></label>)}</fieldset><SubmitButton loading={busy}><KeyRound />Generate key</SubmitButton></form><section className="integration-list"><header><div><small>ACCESS INVENTORY</small><h2>API credentials</h2></div><span>{data.keys.length}</span></header>{data.keys.length ? data.keys.map((key) => <article key={key.id}><span className="integration-record-icon"><KeyRound /></span><div><strong>{key.name}</strong><code>{key.prefix}••••••••••••</code><small>{key.scopes.join(" · ")}</small></div><em className={key.status.toLowerCase()}>{key.status}</em>{key.status === "Active" && <button className="danger-link" onClick={() => revokeKey(key.id)}>Revoke</button>}</article>) : <div className="integration-empty"><KeyRound /><p>No API credentials created yet.</p></div>}</section></div>}
    {tab === "webhooks" && <div className="integration-grid"><form className="integration-builder" onSubmit={createWebhook}><header><span><Link2 /></span><div><small>EVENT DELIVERY</small><h2>Add webhook endpoint</h2><p>Production endpoints require public HTTPS and receive an HMAC-SHA256 signature.</p></div></header><label><span>Endpoint name</span><input value={hookForm.name} onChange={(event) => setHookForm({ ...hookForm, name: event.target.value })} placeholder="Operations platform" required /></label><label><span>Destination URL</span><input type="url" value={hookForm.url} onChange={(event) => setHookForm({ ...hookForm, url: event.target.value })} placeholder="https://example.com/webhooks/innovex" required /></label><fieldset><legend>Subscribe to events</legend><div className="integration-event-grid">{data.options.events.map((eventName) => <label key={eventName} className="integration-check"><input type="checkbox" checked={hookForm.events.includes(eventName)} onChange={() => toggle(hookForm.events, eventName, setHookForm, "events")} /><span><Check />{eventName.replaceAll("_", " ")}</span></label>)}</div></fieldset><SubmitButton loading={busy}><Webhook />Create endpoint</SubmitButton></form><section className="integration-list"><header><div><small>DESTINATIONS</small><h2>Webhook endpoints</h2></div><span>{data.endpoints.length}</span></header>{data.endpoints.length ? data.endpoints.map((endpoint) => <article key={endpoint.id} className="webhook-record"><span className="integration-record-icon"><Webhook /></span><div><strong>{endpoint.name}</strong><code>{endpoint.url}</code><small>{endpoint.events.length} events · secret {endpoint.secretPrefix}</small></div><em className={endpoint.status.toLowerCase()}>{endpoint.status}</em><div className="integration-row-actions"><button title={endpoint.status === "Active" ? "Pause" : "Activate"} onClick={() => changeEndpoint(endpoint, endpoint.status === "Active" ? "Paused" : "Active")}>{endpoint.status === "Active" ? <Pause /> : <Play />}</button><button title="Rotate secret" onClick={() => rotateSecret(endpoint.id)}><RotateCw /></button></div></article>) : <div className="integration-empty"><Webhook /><p>No webhook endpoints configured.</p></div>}</section></div>}
    {tab === "deliveries" && <section className="delivery-panel"><header><div><small>OBSERVABILITY</small><h2>Webhook delivery log</h2><p>Failed deliveries retry with exponential backoff for up to 24 hours.</p></div><button onClick={load}><RefreshCw />Refresh</button></header><div className="delivery-table"><header><span>Event</span><span>Endpoint</span><span>Status</span><span>Attempts</span><span>Response</span><span>Created</span><span /></header>{data.deliveries.map((delivery) => <article key={delivery._id}><code>{delivery.event}</code><span>{delivery.endpoint?.name || "Removed endpoint"}</span><em className={delivery.status.toLowerCase()}>{delivery.status}</em><span>{delivery.attempts}</span><span>{delivery.responseStatus || delivery.lastError || "Queued"}</span><time>{new Date(delivery.createdAt).toLocaleString("en-GB")}</time>{["Failed", "Retrying"].includes(delivery.status) ? <button onClick={() => retryDelivery(delivery._id)}><RefreshCw />Retry</button> : <span />}</article>)}</div>{!data.deliveries.length && <div className="integration-empty"><Activity /><p>Webhook activity will appear here.</p></div>}</section>}
    {revealed && <div className="integration-secret-backdrop" role="dialog" aria-modal="true"><section className="integration-secret-card"><button className="secret-close" onClick={() => setRevealed(null)}><X /></button><span className="secret-shield"><ShieldCheck /></span><small>{revealed.label}</small><h2>{revealed.title}</h2><p>{revealed.warning}</p><code>{revealed.value}</code><button className="secret-copy" onClick={() => navigator.clipboard.writeText(revealed.value)}><Copy />Copy securely</button></section></div>}
  </div>;
}
