import { useEffect, useState } from "react";
import { CalendarClock, CheckCircle2, Clock3, MailCheck, Plus, Send, ShieldCheck, Trash2, UserRoundCheck, X } from "lucide-react";
import { api } from "../../api/client.js";
import AdminSectionHero from "../../components/AdminSectionHero.jsx";
import StatusMessage from "../../components/StatusMessage.jsx";
import SubmitButton from "../../components/SubmitButton.jsx";

const initial = { candidateName: "", candidateEmail: "", candidatePhone: "", jobTitle: "", clientName: "", interviewType: "Teams", location: "", instructions: "", slots: [""] };
const displayDate = (value) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";

export default function AdminScheduling() {
  const [requests, setRequests] = useState([]); const [form, setForm] = useState(initial); const [status, setStatus] = useState(null); const [saving, setSaving] = useState(false);
  async function load() { try { setRequests(await api("/scheduling")); } catch (error) { setStatus({ type: "error", message: error.message }); } }
  useEffect(() => { load(); }, []);
  function setSlot(index, value) { setForm({ ...form, slots: form.slots.map((slot, itemIndex) => itemIndex === index ? value : slot) }); }
  async function sendRequest(event) { event.preventDefault(); setSaving(true); setStatus(null); try { const result = await api("/scheduling", { method: "POST", body: { ...form, slots: form.slots.filter(Boolean).map((value) => new Date(value).toISOString()) } }); setStatus({ type: result.emailDelivery === "Sent" ? "success" : "error", message: result.emailDelivery === "Sent" ? "Scheduling request sent to the candidate portal and email." : `Request created, but email was not sent: ${result.emailReason || "SMTP is not configured"}` }); setForm(initial); await load(); } catch (error) { setStatus({ type: "error", message: error.message }); } finally { setSaving(false); } }
  async function cancelRequest(id) { if (!window.confirm("Cancel this open scheduling request?")) return; try { await api(`/scheduling/${id}/cancel`, { method: "PATCH" }); await load(); } catch (error) { setStatus({ type: "error", message: error.message }); } }
  const open = requests.filter((item) => item.status === "Sent").length; const booked = requests.filter((item) => item.status === "Booked").length;
  return <div className="scheduling-page"><AdminSectionHero icon={CalendarClock} eyebrow="Candidate experience" title="Interview Self-Scheduling" description="Offer controlled time slots and let portal candidates confirm one without email back-and-forth." aside={<div className="workspace-hero-count"><Clock3 /><span><small>AWAITING CHOICE</small><strong>{open}</strong></span></div>} /><StatusMessage status={status} />
    <section className="scheduling-stats"><article><Send /><span><small>OPEN REQUESTS</small><strong>{open}</strong></span></article><article><CheckCircle2 /><span><small>CONFIRMED</small><strong>{booked}</strong></span></article><article><ShieldCheck /><span><small>BOOKING POLICY</small><strong>Portal only</strong></span></article></section>
    <div className="scheduling-layout"><form className="scheduling-builder" onSubmit={sendRequest}><header><span><CalendarClock /></span><div><small>NEW SLOT REQUEST</small><h2>Offer interview times</h2><p>The candidate must have an active Candidate Portal account.</p></div></header><div className="scheduling-form-grid"><label><span>Candidate name</span><input value={form.candidateName} onChange={(event) => setForm({ ...form, candidateName: event.target.value })} required /></label><label><span>Candidate email</span><input type="email" value={form.candidateEmail} onChange={(event) => setForm({ ...form, candidateEmail: event.target.value })} required /></label><label><span>Candidate phone</span><input value={form.candidatePhone} onChange={(event) => setForm({ ...form, candidatePhone: event.target.value })} required /></label><label><span>Job title</span><input value={form.jobTitle} onChange={(event) => setForm({ ...form, jobTitle: event.target.value })} required /></label><label><span>Client / company</span><input value={form.clientName} onChange={(event) => setForm({ ...form, clientName: event.target.value })} required /></label><label><span>Interview type</span><select value={form.interviewType} onChange={(event) => setForm({ ...form, interviewType: event.target.value })}>{["Phone", "Teams", "Zoom", "Face-to-face"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="wide"><span>Location or meeting note</span><input value={form.location} onChange={(event) => setForm({ ...form, location: event.target.value })} placeholder="Teams link will follow, or site address" /></label><label className="wide"><span>Candidate instructions</span><textarea value={form.instructions} onChange={(event) => setForm({ ...form, instructions: event.target.value })} placeholder="Who to ask for, preparation notes or arrival instructions" /></label></div><fieldset className="slot-builder"><legend>Available slots <small>Maximum 12</small></legend>{form.slots.map((slot, index) => <div key={index}><Clock3 /><input type="datetime-local" value={slot} min={new Date(Date.now() + 3600000).toISOString().slice(0, 16)} onChange={(event) => setSlot(index, event.target.value)} required />{form.slots.length > 1 && <button type="button" onClick={() => setForm({ ...form, slots: form.slots.filter((_, itemIndex) => itemIndex !== index) })}><X /></button>}</div>)}{form.slots.length < 12 && <button type="button" className="add-slot" onClick={() => setForm({ ...form, slots: [...form.slots, ""] })}><Plus />Add another slot</button>}</fieldset><SubmitButton loading={saving}><Send />Send slot request</SubmitButton></form>
      <section className="scheduling-register"><header><div><small>REQUEST REGISTER</small><h2>Scheduling activity</h2></div><span>{requests.length}</span></header>{requests.map((request) => <article key={request._id}><span className={`schedule-status-icon ${request.status.toLowerCase()}`}>{request.status === "Booked" ? <CheckCircle2 /> : <MailCheck />}</span><div className="schedule-record-copy"><strong>{request.candidateName}</strong><small>{request.jobTitle} · {request.clientName}</small><p>{request.status === "Booked" ? `Confirmed ${displayDate(request.interview?.interviewDate || request.bookedAt)}` : `${request.slots.filter((slot) => slot.status === "Available").length} slots · expires ${displayDate(request.expiresAt)}`}</p></div><em className={request.status.toLowerCase()}>{request.status}</em>{request.status === "Sent" && <button title="Cancel request" onClick={() => cancelRequest(request._id)}><Trash2 /></button>}</article>)}{!requests.length && <div className="schedule-empty"><UserRoundCheck /><strong>No scheduling requests yet</strong><p>Offer the first set of times to an activated portal candidate.</p></div>}</section>
    </div></div>;
}
