import { useEffect, useMemo, useState } from "react";
import { Building2, Copy, ExternalLink, KeyRound, Send, ShieldCheck, UserRoundCheck, UsersRound } from "lucide-react";
import { api } from "../../api/client.js";
import AdminSectionHero from "../../components/AdminSectionHero.jsx";
import StatusMessage from "../../components/StatusMessage.jsx";

export default function AdminPortals() {
  const [data, setData] = useState({ accounts: [], candidates: [], clients: [] });
  const [type, setType] = useState("Candidate");
  const [subjectId, setSubjectId] = useState("");
  const [status, setStatus] = useState(null);
  const [latestLink, setLatestLink] = useState("");
  const options = useMemo(() => type === "Candidate" ? data.candidates : data.clients, [data, type]);
  async function load() { try { setData(await api("/portal-admin")); } catch (error) { setStatus({ type: "error", message: error.message }); } }
  useEffect(() => { load(); }, []);
  async function invite(event) {
    event.preventDefault(); const subject = options.find((item) => item._id === subjectId); const email = type === "Candidate" ? subject?.email : subject?.primaryContact?.email || subject?.contacts?.find((item) => item.email)?.email;
    if (!subject || !email) return setStatus({ type: "error", message: "Select a record with a valid email address." });
    try { const result = await api("/portal-admin/invite", { method: "POST", body: { type, subjectId, name: subject.name, email } }); setLatestLink(result.invitationUrl); setStatus({ message: result.message }); setSubjectId(""); load(); } catch (error) { setStatus({ type: "error", message: error.message }); }
  }
  async function changeStatus(account, next) { try { const result = await api(`/portal-admin/${account._id}/status`, { method: "PATCH", body: { status: next } }); setStatus({ message: result.message }); load(); } catch (error) { setStatus({ type: "error", message: error.message }); } }
  return <div className="portal-admin-page"><AdminSectionHero icon={KeyRound} eyebrow="Secure collaboration" title="Candidate & Client Portals" description="Invite external users into a controlled, tenant-isolated experience without exposing the internal CRM." aside={<div className="workspace-hero-count"><UsersRound size={18} /><span><small>ACTIVE PORTALS</small><strong>{data.accounts.filter((account) => account.status === "Active").length}</strong></span></div>} /><StatusMessage status={status} />
    <section className="portal-invite-card"><header><div><small>NEW SECURE ACCESS</small><h2>Invite to a portal</h2><p>Activation links expire after seven days. Existing sessions are revoked when access changes.</p></div><ShieldCheck /></header><form onSubmit={invite}><label><span>Portal type</span><div className="portal-type-toggle"><button type="button" className={type === "Candidate" ? "active" : ""} onClick={() => { setType("Candidate"); setSubjectId(""); }}><UserRoundCheck />Candidate</button><button type="button" className={type === "Client" ? "active" : ""} onClick={() => { setType("Client"); setSubjectId(""); }}><Building2 />Client</button></div></label><label><span>{type} record</span><select value={subjectId} onChange={(event) => setSubjectId(event.target.value)} required><option value="">Select {type.toLowerCase()}</option>{options.map((item) => <option value={item._id} key={item._id}>{item.name} · {type === "Candidate" ? item.email : item.primaryContact?.email || item.contacts?.find((contact) => contact.email)?.email || "No email"}</option>)}</select></label><button className="button"><Send />Send secure invitation</button></form>{latestLink && <div className="portal-link-result"><div><strong>Latest activation link</strong><span>Email delivery may depend on SMTP configuration. Copy it securely if needed.</span></div><button onClick={() => navigator.clipboard.writeText(latestLink)}><Copy />Copy link</button><a href={latestLink} target="_blank" rel="noreferrer"><ExternalLink />Open</a></div>}</section>
    <section className="portal-account-register"><header><div><small>ACCESS REGISTER</small><h2>External portal accounts</h2></div><strong>{data.accounts.length}</strong></header><div><div className="portal-account-head"><span>Person</span><span>Portal</span><span>Linked record</span><span>Status</span><span>Last sign-in</span><span /></div>{data.accounts.map((account) => <article key={account._id}><span><strong>{account.name}</strong><small>{account.email}</small></span><span><b className={`portal-kind ${account.type.toLowerCase()}`}>{account.type}</b></span><span>{account.candidate?.name || account.clientAccount?.name || "Record unavailable"}</span><span><b className={`portal-access-status ${account.status.toLowerCase()}`}>{account.status}</b></span><span>{account.lastLoginAt ? new Date(account.lastLoginAt).toLocaleDateString("en-GB") : "Never"}</span><span>{account.status === "Active" ? <button onClick={() => changeStatus(account, "Suspended")}>Suspend</button> : account.status === "Suspended" ? <button onClick={() => changeStatus(account, "Active")}>Reactivate</button> : <small>Invitation pending</small>}</span></article>)}</div>{!data.accounts.length && <div className="automation-empty"><KeyRound /><strong>No portal accounts</strong><span>Invite a candidate or client to start secure collaboration.</span></div>}</section>
  </div>;
}
