import { useEffect, useMemo, useState } from "react";
import { BarChart3, BriefcaseBusiness, Clock3, Coins, TrendingUp, UserCheck, UsersRound } from "lucide-react";
import { api } from "../../api/client.js";
import AdminSectionHero from "../../components/AdminSectionHero.jsx";
import StatusMessage from "../../components/StatusMessage.jsx";

const money = (value) => new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP", maximumFractionDigits: 0 }).format(Number(value || 0));

export default function AdminReports() {
  const [days, setDays] = useState(365);
  const [data, setData] = useState(null);
  const [status, setStatus] = useState(null);
  async function load(period = days) { try { setData(await api(`/analytics/recruitment?days=${period}`)); } catch (error) { setStatus({ type: "error", message: error.message }); } }
  useEffect(() => { load(); }, []);
  const maxFunnel = useMemo(() => Math.max(1, ...(data?.funnel || []).map((item) => item.count)), [data]);
  const maxSource = useMemo(() => Math.max(1, ...(data?.sourceQuality || []).map((item) => item.candidates)), [data]);
  const maxApplications = useMemo(() => Math.max(1, ...(data?.applicationSources || []).map((item) => item.applications)), [data]);
  if (!data) return <div className="admin-loading-screen">Preparing recruitment analytics…</div>;
  return <div className="reports-page"><AdminSectionHero icon={BarChart3} eyebrow="Decision intelligence" title="Recruitment Analytics" description="Understand pipeline conversion, source quality, recruiter performance, time-to-fill and commercial outcomes." aside={<div className="workspace-hero-count"><TrendingUp size={18} /><span><small>PLACEMENTS</small><strong>{data.metrics.placements}</strong></span></div>} /><StatusMessage status={status} />
    <div className="reports-period"><span>Reporting period</span><select value={days} onChange={(event) => { const period = Number(event.target.value); setDays(period); load(period); }}><option value="90">Last 90 days</option><option value="180">Last 6 months</option><option value="365">Last 12 months</option><option value="730">Last 24 months</option></select></div>
    <section className="reports-kpis"><article><BriefcaseBusiness /><div><small>Open vacancies</small><strong>{data.metrics.openVacancies}</strong></div></article><article><UsersRound /><div><small>New candidates</small><strong>{data.metrics.candidates}</strong></div></article><article><Clock3 /><div><small>Average time to fill</small><strong>{data.metrics.averageTimeToFillDays}d</strong></div></article><article><UserCheck /><div><small>Interview → placement</small><strong>{data.metrics.interviewToPlacementRate}%</strong></div></article>{data.finance && <article><Coins /><div><small>Placement revenue</small><strong>{money(data.finance.placementRevenue)}</strong></div></article>}</section>
    <section className="reports-grid"><article className="report-card"><header><div><small>PIPELINE HEALTH</small><h2>Candidate funnel</h2></div><BarChart3 /></header><div className="funnel-chart">{data.funnel.map((item) => <div key={item.stage}><span>{item.stage}</span><i><b style={{ width: `${Math.max(5, (item.count / maxFunnel) * 100)}%` }} /></i><strong>{item.count}</strong></div>)}{!data.funnel.length && <p>No pipeline data in this period.</p>}</div></article><article className="report-card"><header><div><small>TALENT ACQUISITION</small><h2>Candidate source quality</h2></div><TrendingUp /></header><div className="source-chart">{data.sourceQuality.map((item) => <div key={item.source}><header><span>{item.source}</span><strong>{item.conversionRate}% placed</strong></header><i><b style={{ width: `${Math.max(4, (item.candidates / maxSource) * 100)}%` }} /></i><small>{item.candidates} candidates · {item.placements} placements</small></div>)}{!data.sourceQuality.length && <p>No candidate source data in this period.</p>}</div></article><article className="report-card"><header><div><small>JOB DISTRIBUTION</small><h2>Application source conversion</h2></div><BriefcaseBusiness /></header><div className="source-chart">{(data.applicationSources || []).map((item) => <div key={item.source}><header><span>{item.source}</span><strong>{item.conversionRate}% shortlisted</strong></header><i><b style={{ width: `${Math.max(4, (item.applications / maxApplications) * 100)}%` }} /></i><small>{item.applications} applications · {item.shortlisted} shortlisted</small></div>)}{!data.applicationSources?.length && <p>UTM and referrer attribution will appear as applications arrive.</p>}</div></article></section>
    <section className="report-card recruiter-scorecard"><header><div><small>TEAM PERFORMANCE</small><h2>Recruiter scorecard</h2></div><UsersRound /></header><div className="scorecard-table"><header><span>Recruiter</span><span>Submitted</span><span>Client review</span><span>Hired</span><span>Conversion</span></header>{data.recruiterPerformance.map((item) => <article key={item._id || item.name}><strong>{item.name || "Unassigned"}</strong><span>{item.submitted}</span><span>{item.clientReview}</span><span>{item.hired}</span><b>{item.conversionRate}%</b></article>)}{!data.recruiterPerformance.length && <p>No recruiter submissions in this period.</p>}</div></section>
    {data.finance && <section className="reports-finance"><article><small>Invoiced</small><strong>{money(data.finance.invoiced)}</strong></article><article><small>Collected</small><strong>{money(data.finance.collected)}</strong></article><article><small>Outstanding</small><strong>{money(data.finance.outstanding)}</strong></article></section>}
  </div>;
}
