import "./tenancy/tenantPlugin.js";
import cors from "cors";
import dotenv from "dotenv";
import express from "express";
import helmet from "helmet";
import morgan from "morgan";
import rateLimit from "express-rate-limit";
import applicationRoutes from "./routes/applicationRoutes.js";
import analyticsRoutes from "./routes/analyticsRoutes.js";
import automationRoutes from "./routes/automationRoutes.js";
import archiveRoutes from "./routes/archiveRoutes.js";
import attendanceRoutes from "./routes/attendanceRoutes.js";
import authRoutes from "./routes/authRoutes.js";
import blogRoutes from "./routes/blogRoutes.js";
import businessLeadRoutes from "./routes/businessLeadRoutes.js";
import callRoutes from "./routes/callRoutes.js";
import candidateRoutes from "./routes/candidateRoutes.js";
import candidateCvRoutes from "./routes/candidateCvRoutes.js";
import candidateCommunicationRoutes from "./routes/candidateCommunicationRoutes.js";
import clientAccountRoutes from "./routes/clientAccountRoutes.js";
import contactRoutes from "./routes/contactRoutes.js";
import complianceRoutes from "./routes/complianceRoutes.js";
import courseRoutes from "./routes/courseRoutes.js";
import cvRoutes from "./routes/cvRoutes.js";
import dashboardRoutes from "./routes/dashboardRoutes.js";
import emailRoutes from "./routes/emailRoutes.js";
import employeeSuggestionRoutes from "./routes/employeeSuggestionRoutes.js";
import financeRoutes from "./routes/financeRoutes.js";
import hrRoutes from "./routes/hrRoutes.js";
import interviewRoutes from "./routes/interviewRoutes.js";
import integrationRoutes from "./routes/integrationRoutes.js";
import jobRoutes from "./routes/jobRoutes.js";
import meetingRoutes from "./routes/meetingRoutes.js";
import newsletterRoutes from "./routes/newsletterRoutes.js";
import organizationRoutes from "./routes/organizationRoutes.js";
import operationsRoutes from "./routes/operationsRoutes.js";
import partnerRoutes from "./routes/partnerRoutes.js";
import portalNotificationRoutes from "./routes/portalNotificationRoutes.js";
import portalRoutes from "./routes/portalRoutes.js";
import portalAdminRoutes from "./routes/portalAdminRoutes.js";
import publicApiRoutes from "./routes/publicApiRoutes.js";
import recruitmentWorkflowRoutes from "./routes/recruitmentWorkflowRoutes.js";
import seoRoutes from "./routes/seoRoutes.js";
import schedulingRoutes from "./routes/schedulingRoutes.js";
import testimonialRoutes from "./routes/testimonialRoutes.js";
import termsRoutes from "./routes/termsRoutes.js";
import trainingBookingRoutes from "./routes/trainingBookingRoutes.js";
import trainingQuotationRoutes from "./routes/trainingQuotationRoutes.js";
import userRoutes from "./routes/userRoutes.js";
import vacancyIntelligenceRoutes from "./routes/vacancyIntelligenceRoutes.js";
import webLeadRoutes from "./routes/webLeadRoutes.js";
import { errorHandler, notFound } from "./middleware/errorHandler.js";
import { resolveTenant } from "./middleware/tenant.js";

dotenv.config();

const app = express();

app.use(helmet({
  crossOriginResourcePolicy: { policy: "same-site" },
  referrerPolicy: { policy: "no-referrer" },
  strictTransportSecurity: { maxAge: 31536000, includeSubDomains: true, preload: true }
}));
app.use(cors({ origin: process.env.CLIENT_URL || "http://localhost:5173", credentials: true }));
app.use("/api", (req, res, next) => {
  res.set("Cache-Control", "no-store, max-age=0");
  res.set("Pragma", "no-cache");
  next();
});
app.use(express.json({ limit: "1mb" }));
app.use(express.urlencoded({ extended: true }));
app.use(morgan("dev"));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: 300, standardHeaders: true, legacyHeaders: false }));

app.get("/api/health", (req, res) => res.json({ status: "ok", service: "Innovex API" }));
app.use("/api", resolveTenant);
app.use("/api", seoRoutes);
app.use("/api/auth", authRoutes);
app.use("/api/v1", publicApiRoutes);
app.use("/api/blogs", blogRoutes);
app.use("/api/business-leads", businessLeadRoutes);
app.use("/api/calls", callRoutes);
app.use("/api/candidates", candidateRoutes);
app.use("/api/candidate-cvs", candidateCvRoutes);
app.use("/api/candidate-communications", candidateCommunicationRoutes);
app.use("/api/client-accounts", clientAccountRoutes);
app.use("/api/jobs", jobRoutes);
app.use("/api/applications", applicationRoutes);
app.use("/api/analytics", analyticsRoutes);
app.use("/api/automations", automationRoutes);
app.use("/api/archive", archiveRoutes);
app.use("/api/portal-notifications", portalNotificationRoutes);
app.use("/api/portal", portalRoutes);
app.use("/api/portal-admin", portalAdminRoutes);
app.use("/api/recruitment-workflow", recruitmentWorkflowRoutes);
app.use("/api/attendance", attendanceRoutes);
app.use("/api/cv-uploads", cvRoutes);
app.use("/api/testimonials", testimonialRoutes);
app.use("/api/terms", termsRoutes);
app.use("/api/partners", partnerRoutes);
app.use("/api/contact", contactRoutes);
app.use("/api/compliance", complianceRoutes);
app.use("/api/dashboard", dashboardRoutes);
app.use("/api/emails", emailRoutes);
app.use("/api/employee-suggestions", employeeSuggestionRoutes);
app.use("/api/finance", financeRoutes);
app.use("/api/hr", hrRoutes);
app.use("/api/interviews", interviewRoutes);
app.use("/api/scheduling", schedulingRoutes);
app.use("/api/integrations", integrationRoutes);
app.use("/api/meetings", meetingRoutes);
app.use("/api/newsletters", newsletterRoutes);
app.use("/api/organizations", organizationRoutes);
app.use("/api/operations", operationsRoutes);
app.use("/api/courses", courseRoutes);
app.use("/api/training-bookings", trainingBookingRoutes);
app.use("/api/training-quotations", trainingQuotationRoutes);
app.use("/api/users", userRoutes);
app.use("/api/vacancy-intelligence", vacancyIntelligenceRoutes);
app.use("/api/web-leads", webLeadRoutes);

app.use(notFound);
app.use(errorHandler);

export default app;
